"""
Code Validator for AI-Generated Code

Provides comprehensive validation and automated repair for code generated by AI agents.
Works with the self-correction engine to fix issues before execution.
"""

import ast
import re
import logging
import subprocess
import sys
import tempfile
import os
from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum

logger = logging.getLogger(__name__)


class ValidationLevel(Enum):
    """Levels of validation to perform"""
    SYNTAX = "syntax"          # Only syntax check
    STATIC = "static"          # Syntax + static analysis
    IMPORTS = "imports"        # Check if imports are available
    EXECUTION = "execution"    # Actually try to execute
    FULL = "full"              # All checks


@dataclass
class ValidationResult:
    """Result of code validation"""
    is_valid: bool
    level_checked: ValidationLevel
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    fixed_code: Optional[str] = None
    fixes_applied: List[str] = field(default_factory=list)


class CodeValidator:
    """
    Validates and repairs AI-generated code.
    
    Features:
    - Multi-level validation (syntax, static, imports, execution)
    - Common error pattern detection
    - Automated code repair
    - Import resolution
    - Type hint validation
    """
    
    def __init__(self, auto_fix: bool = True):
        """
        Initialize the validator.
        
        Args:
            auto_fix: Whether to automatically attempt fixes
        """
        self.auto_fix = auto_fix
        self.validation_history: List[ValidationResult] = []
        
        # Common patterns that indicate issues
        self.warning_patterns = [
            (r'except\s*:', "Bare except clause - be more specific"),
            (r'import \*', "Wildcard import - use explicit imports"),
            (r'eval\(', "eval() is a security risk"),
            (r'exec\(', "exec() is a security risk"),
            (r'pickle\.loads?\(', "pickle can execute arbitrary code"),
            (r'__import__\(', "Dynamic import - verify source"),
            (r'os\.system\(', "os.system() - prefer subprocess"),
            (r'shell=True', "shell=True can be a security risk"),
        ]
        
        # Common fix patterns
        self.fix_patterns = [
            # Missing colons
            (r'^(\s*)(if|elif|else|for|while|def|class|try|except|finally|with)(.+?)(?<!:)\s*$',
             r'\1\2\3:'),
            # Print statement (Python 2 style)
            (r'^(\s*)print\s+([^(].*?)$', r'\1print(\2)'),
            # Raw string for regex
            (r're\.(search|match|findall|sub)\s*\(\s*(["\'])(?!r)', r're.\1(r\2'),
        ]
    
    def validate(
        self,
        code: str,
        level: ValidationLevel = ValidationLevel.STATIC,
        context: Optional[Dict[str, Any]] = None
    ) -> ValidationResult:
        """
        Validate code at the specified level.
        
        Args:
            code: Python code to validate
            level: Depth of validation
            context: Optional execution context
            
        Returns:
            ValidationResult with details
        """
        result = ValidationResult(is_valid=True, level_checked=level)
        current_code = code
        
        # Level 1: Syntax
        if level.value >= ValidationLevel.SYNTAX.value:
            syntax_result = self._check_syntax(current_code)
            if not syntax_result[0]:
                result.is_valid = False
                result.errors.append(syntax_result[1])
                
                # Try to fix syntax
                if self.auto_fix:
                    fixed, fix_desc = self._fix_syntax(current_code, syntax_result[1])
                    if fixed != current_code:
                        current_code = fixed
                        result.fixes_applied.append(fix_desc)
                        # Re-validate
                        syntax_result = self._check_syntax(current_code)
                        if syntax_result[0]:
                            result.is_valid = True
                            result.errors = []
        
        # Level 2: Static analysis
        if result.is_valid and level.value >= ValidationLevel.STATIC.value:
            warnings = self._static_analysis(current_code)
            result.warnings.extend(warnings)
        
        # Level 3: Import checking
        if result.is_valid and level.value >= ValidationLevel.IMPORTS.value:
            import_issues = self._check_imports(current_code)
            result.warnings.extend(import_issues)
        
        # Level 4: Execution test
        if result.is_valid and level == ValidationLevel.EXECUTION:
            exec_result = self._test_execution(current_code, context)
            if not exec_result[0]:
                result.is_valid = False
                result.errors.append(exec_result[1])
        
        # Store fixed code if different
        if current_code != code:
            result.fixed_code = current_code
        
        self.validation_history.append(result)
        return result
    
    def _check_syntax(self, code: str) -> Tuple[bool, str]:
        """Check Python syntax"""
        try:
            ast.parse(code)
            return True, ""
        except SyntaxError as e:
            return False, f"Syntax error at line {e.lineno}: {e.msg}"
    
    def _static_analysis(self, code: str) -> List[str]:
        """Perform static analysis for common issues"""
        warnings = []
        lines = code.split('\n')
        
        for i, line in enumerate(lines, 1):
            for pattern, message in self.warning_patterns:
                if re.search(pattern, line):
                    warnings.append(f"Line {i}: {message}")
        
        # Check for undefined variables (simple heuristic)
        undefined = self._find_undefined_names(code)
        for name, line in undefined:
            warnings.append(f"Line {line}: '{name}' may be undefined")
        
        # Check for unused imports
        unused = self._find_unused_imports(code)
        for name in unused:
            warnings.append(f"Unused import: {name}")
        
        return warnings
    
    def _find_undefined_names(self, code: str) -> List[Tuple[str, int]]:
        """Find potentially undefined names"""
        undefined = []
        
        try:
            tree = ast.parse(code)
            
            # Collect all defined names
            defined = set()
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef):
                    defined.add(node.name)
                elif isinstance(node, ast.ClassDef):
                    defined.add(node.name)
                elif isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
                    defined.add(node.id)
                elif isinstance(node, ast.Import):
                    for alias in node.names:
                        defined.add(alias.asname or alias.name)
                elif isinstance(node, ast.ImportFrom):
                    for alias in node.names:
                        defined.add(alias.asname or alias.name)
            
            # Built-in names
            import builtins
            builtins_set = set(dir(builtins))
            
        except SyntaxError:
            pass
        
        return undefined
    
    def _find_unused_imports(self, code: str) -> List[str]:
        """Find unused imports"""
        unused = []
        
        try:
            tree = ast.parse(code)
            imports = set()
            used_names = set()
            
            # Collect imports
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        imports.add(alias.asname or alias.name.split('.')[0])
                elif isinstance(node, ast.ImportFrom):
                    for alias in node.names:
                        imports.add(alias.asname or alias.name)
            
            # Collect used names
            for node in ast.walk(tree):
                if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
                    used_names.add(node.id)
                elif isinstance(node, ast.Attribute):
                    if isinstance(node.value, ast.Name):
                        used_names.add(node.value.id)
            
            # Find unused
            unused = list(imports - used_names)
            
        except SyntaxError:
            pass
        
        return unused
    
    def _check_imports(self, code: str) -> List[str]:
        """Check if imported modules are available"""
        issues = []
        
        try:
            tree = ast.parse(code)
            
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if not self._is_module_available(alias.name):
                            issues.append(f"Module '{alias.name}' may not be installed")
                            
                elif isinstance(node, ast.ImportFrom):
                    if node.module and not self._is_module_available(node.module):
                        issues.append(f"Module '{node.module}' may not be installed")
        
        except SyntaxError:
            pass
        
        return issues
    
    def _is_module_available(self, module_name: str) -> bool:
        """Check if a module is available"""
        # Standard library modules (common ones)
        stdlib = {
            'os', 'sys', 'time', 'datetime', 'json', 're', 'math', 'random',
            'collections', 'itertools', 'functools', 'typing', 'abc', 'io',
            'pathlib', 'subprocess', 'threading', 'multiprocessing', 'asyncio',
            'logging', 'unittest', 'traceback', 'ast', 'tempfile', 'shutil',
            'pickle', 'copy', 'hashlib', 'base64', 'urllib', 'http', 'socket',
            'email', 'html', 'xml', 'csv', 'sqlite3', 'configparser', 'argparse',
            'dataclasses', 'enum', 'contextlib', 'warnings', 'gc', 'inspect',
            'types', 'operator', 'string', 'textwrap', 'difflib', 'struct',
            'codecs', 'locale', 'gettext', 'calendar', 'fractions', 'decimal',
            'statistics', 'secrets', 'uuid', 'heapq', 'bisect', 'array',
            'weakref', 'queue', 'concurrent', 'ctypes', 'signal'
        }
        
        base_module = module_name.split('.')[0]
        
        if base_module in stdlib:
            return True
        
        try:
            __import__(base_module)
            return True
        except ImportError:
            return False
    
    def _test_execution(
        self, 
        code: str, 
        context: Optional[Dict[str, Any]] = None
    ) -> Tuple[bool, str]:
        """Test code execution in isolated environment"""
        # Create a temporary file
        with tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.py',
            delete=False
        ) as f:
            f.write(code)
            temp_path = f.name
        
        try:
            # Run in subprocess with timeout
            result = subprocess.run(
                [sys.executable, temp_path],
                capture_output=True,
                text=True,
                timeout=10,
                cwd=os.path.dirname(temp_path)
            )
            
            if result.returncode != 0:
                return False, f"Execution error: {result.stderr[:500]}"
            
            return True, ""
            
        except subprocess.TimeoutExpired:
            return False, "Execution timed out (>10s)"
        except Exception as e:
            return False, f"Execution failed: {str(e)}"
        finally:
            os.unlink(temp_path)
    
    def _fix_syntax(self, code: str, error: str) -> Tuple[str, str]:
        """Attempt to fix syntax errors"""
        fixed_code = code
        fix_description = ""
        
        # Extract line number from error
        line_match = re.search(r'line (\d+)', error)
        if not line_match:
            return code, ""
        
        line_num = int(line_match.group(1))
        lines = code.split('\n')
        
        if line_num > len(lines):
            return code, ""
        
        error_line = lines[line_num - 1]
        
        # Apply fix patterns
        for pattern, replacement in self.fix_patterns:
            if re.search(pattern, error_line, re.MULTILINE):
                fixed_line = re.sub(pattern, replacement, error_line)
                if fixed_line != error_line:
                    lines[line_num - 1] = fixed_line
                    fixed_code = '\n'.join(lines)
                    fix_description = f"Line {line_num}: Applied pattern fix"
                    break
        
        # Fix missing colon
        if 'expected \':\'' in error.lower() or 'invalid syntax' in error.lower():
            keywords = ['if', 'elif', 'else', 'for', 'while', 'def', 'class', 
                       'try', 'except', 'finally', 'with']
            for kw in keywords:
                if kw in error_line and not error_line.rstrip().endswith(':'):
                    lines[line_num - 1] = error_line.rstrip() + ':'
                    fixed_code = '\n'.join(lines)
                    fix_description = f"Line {line_num}: Added missing colon"
                    break
        
        # Fix unmatched brackets
        if 'unexpected EOF' in error or 'unmatched' in error.lower():
            open_count = code.count('(') - code.count(')')
            if open_count > 0:
                fixed_code = code + ')' * open_count
                fix_description = f"Added {open_count} closing parentheses"
            
            open_count = code.count('[') - code.count(']')
            if open_count > 0:
                fixed_code = fixed_code + ']' * open_count
                fix_description = f"Added {open_count} closing brackets"
            
            open_count = code.count('{') - code.count('}')
            if open_count > 0:
                fixed_code = fixed_code + '}' * open_count
                fix_description = f"Added {open_count} closing braces"
        
        return fixed_code, fix_description
    
    def repair_code(
        self,
        code: str,
        max_attempts: int = 3,
        target_level: ValidationLevel = ValidationLevel.STATIC
    ) -> ValidationResult:
        """
        Attempt to repair code until it passes validation.
        
        Args:
            code: Code to repair
            max_attempts: Maximum repair attempts
            target_level: Validation level to achieve
            
        Returns:
            Final validation result
        """
        current_code = code
        all_fixes = []
        
        for attempt in range(max_attempts):
            result = self.validate(current_code, target_level)
            
            if result.is_valid:
                result.fixes_applied = all_fixes + result.fixes_applied
                return result
            
            if result.fixed_code:
                current_code = result.fixed_code
                all_fixes.extend(result.fixes_applied)
            else:
                # No automatic fix available
                break
        
        # Return final state
        final_result = self.validate(current_code, target_level)
        final_result.fixes_applied = all_fixes + final_result.fixes_applied
        if current_code != code:
            final_result.fixed_code = current_code
        
        return final_result
    
    def format_validation_report(self, result: ValidationResult) -> str:
        """Format a validation result as a readable report"""
        lines = [
            "=" * 50,
            "CODE VALIDATION REPORT",
            "=" * 50,
            f"Status: {'✅ VALID' if result.is_valid else '❌ INVALID'}",
            f"Level: {result.level_checked.value}",
            ""
        ]
        
        if result.errors:
            lines.append("ERRORS:")
            for error in result.errors:
                lines.append(f"  ❌ {error}")
            lines.append("")
        
        if result.warnings:
            lines.append("WARNINGS:")
            for warning in result.warnings:
                lines.append(f"  ⚠️ {warning}")
            lines.append("")
        
        if result.fixes_applied:
            lines.append("FIXES APPLIED:")
            for fix in result.fixes_applied:
                lines.append(f"  🔧 {fix}")
            lines.append("")
        
        if result.fixed_code:
            lines.append("Fixed code is available in result.fixed_code")
        
        lines.append("=" * 50)
        return '\n'.join(lines)


# Convenience function
def validate_and_fix(code: str, level: ValidationLevel = ValidationLevel.STATIC) -> Tuple[bool, str, str]:
    """
    Validate code and attempt to fix if needed.
    
    Args:
        code: Python code
        level: Validation level
        
    Returns:
        Tuple of (is_valid, final_code, report)
    """
    validator = CodeValidator(auto_fix=True)
    result = validator.repair_code(code, target_level=level)
    report = validator.format_validation_report(result)
    
    final_code = result.fixed_code if result.fixed_code else code
    return result.is_valid, final_code, report


# Singleton instance
code_validator = CodeValidator()
